### ISSUE TITLE
Create commands

### ISSUE THREAD

**Issue by x0rz3q** [b0tweb/b0tweb#9]
- [x] Screenshot
- [x] Video
- [x] Picture from webcam
- [ ] Recording audio
- [ ] Tree of path
- [ ] Execute python
- [x] Execute cmd commands (batch script)
- [x] Key logger
- [ ] Play sound
- [x] Spawn processed
- [x] Show random picture of Richard Stallman
- [x] Stop command (to disconnect client)

**Comment by JurisMajors** [comment]
Working on a CMD command to use as an example for command registry and the pipeline.

**Comment by JurisMajors** [comment]
for keylogger see #12

**Comment by JurisMajors** [comment]
for initial kill switch see #11
